// reactbuildtest/src/App.tsx
import { useState, useEffect } from "react";

export default function App() {
  const [token, setToken] = useState<string | null>(localStorage.getItem("token"));
  const [isLogin, setIsLogin] = useState(true);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [error, setError] = useState("");
  const [users, setUsers] = useState<any[]>([]);

  useEffect(() => {
    if (token) {
      localStorage.setItem("token", token);
      testBackend();
    } else {
      localStorage.removeItem("token");
    }
  }, [token]);

  const testBackend = async () => {
    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}api/health`);
      if (res.ok) {
        const authRes = await fetch(`${import.meta.env.VITE_API_URL}api/users`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        if (authRes.status === 403) {
          setBackendStatus("Connected to backend (Users API blocked: Requires ADMIN role)");
        } else if (authRes.ok) {
          setBackendStatus("Connected to backend! (Users API authenticated)");
          const data = await authRes.json();
          setUsers(data);
        } else {
          setBackendStatus(`Connected to backend (Users API Error: ${authRes.status})`);
        }
      } else {
        setBackendStatus("Backend health check failed.");
      }
    } catch (e) {
      setBackendStatus("Cannot connect to backend. Is it running?");
    }
  };

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    const endpoint = isLogin ? "login" : "register";
    const body = isLogin ? { email, password } : { email, password, name };
    
    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}api/auth/${endpoint}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.message || data.error || "Authentication failed");
      setToken(data.token);
    } catch (err: any) {
      setError(err.message);
    }
  };

  if (!token) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="bg-white p-8 rounded-2xl shadow-xl max-w-md w-full">
          <h1 className="text-2xl font-bold text-center mb-6 text-gray-800">
            {isLogin ? "Welcome Back" : "Create Account"}
          </h1>
          {error && <div className="mb-4 p-3 bg-red-100 text-red-700 rounded-lg text-sm">{error}</div>}
          <form onSubmit={handleAuth} className="space-y-4">
            {!isLogin && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Name</label>
                <input required type="text" value={name} onChange={(e) => setName(e.target.value)} className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
              </div>
            )}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
              <input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
              <input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
            </div>
            <button type="submit" className="w-full bg-blue-600 text-white font-semibold py-2 rounded-lg hover:bg-blue-700 transition">
              {isLogin ? "Sign In" : "Sign Up"}
            </button>
          </form>
          <p className="mt-6 text-center text-sm text-gray-600">
            {isLogin ? "Don't have an account? " : "Already have an account? "}
            <button onClick={() => setIsLogin(!isLogin)} className="text-blue-600 hover:underline font-medium">
              {isLogin ? "Sign Up" : "Sign In"}
            </button>
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="flex items-center justify-between bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <div>
            <h1 className="text-2xl font-bold text-gray-800">Dashboard</h1>
            <p className="text-gray-500">Welcome to your local custom auth boilerplate.</p>
          </div>
          <button onClick={() => setToken(null)} className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg font-medium transition">
            Sign Out
          </button>
        </div>
              <p className="font-medium">{backendStatus}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// qwykz-tests/test-vue-clerk/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { SignIn, SignUp, UserButton, useAuth } from '@clerk/vue'

const isLogin = ref(true)
const backendStatus = ref<string>('Testing connection...')
const { isSignedIn, getToken } = useAuth()

onMounted(() => {
  testBackend()
})

const testBackend = async () => {
  try {
    const res = await fetch(`${import.meta.env.VITE_API_URL}api/health`)
    if (res.ok) {
      const token = await getToken.value()
      if (!token) {
        backendStatus.value = "Connected to backend (Waiting for login to test auth)"
        return
      }
      const authRes = await fetch(`${import.meta.env.VITE_API_URL}api/users`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      if (authRes.status === 403) {
        backendStatus.value = "Connected! (Users API blocked: Requires ADMIN role)"
      } else if (authRes.ok) {
        backendStatus.value = "Connected! (Users API authenticated)"
      } else {
        backendStatus.value = "Connected to backend, but auth failed."
      }
    } else {
      backendStatus.value = "Failed to connect to backend."
    }
  } catch (err) {
    backendStatus.value = "Backend is unreachable. Is it running?"
  }
}
</script>

<template>
  <div v-if="isSignedIn" class="min-h-screen bg-gray-100">
    <nav class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex items-center">
            <h1 class="text-xl font-bold text-gray-900">Dashboard</h1>
          </div>
          <div class="flex items-center">
            <UserButton />
          </div>
        </div>
      </div>
    </nav>

    <main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div class="px-4 py-6 sm:px-0">
        <div class="border-4 border-dashed border-gray-200 rounded-lg p-8 flex flex-col items-center justify-center bg-white space-y-4">
          <h2 class="text-2xl font-semibold text-gray-800">Welcome back!</h2>
          <p class="text-gray-600">You are securely authenticated with Clerk.</p>
          
          <div class="mt-8 p-4 bg-gray-50 rounded-md border border-gray-200 w-full max-w-md text-center">
            <h3 class="font-medium text-gray-900 mb-2">Backend Connection Status:</h3>
            <p class="text-sm" :class="backendStatus.includes('Connected') ? 'text-green-600' : 'text-red-600'">
              {{ backendStatus }}
            </p>
          </div>
        </div>
      </div>
    </main>
  </div>

  <div v-else class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-md flex flex-col items-center">
      <SignIn v-if="isLogin" />
      <SignUp v-else />
      <button 
        @click="isLogin = !isLogin"
        class="mt-4 text-blue-600 hover:underline"
      >
        {{ isLogin ? "Need an account? Sign Up" : "Already have an account? Sign In" }}
      </button>
    </div>
  </div>
</template>
